import { StateGraphArgs } from "@langchain/langgraph";
import { Annotation } from "@langchain/langgraph";

/**
 * Core state for the Socialyncara Intelligence Layer
 */
export const AgentState = Annotation.Root({
    userId: Annotation<string>(),
    topic: Annotation<string>(),
    audience: Annotation<string>(),
    tone: Annotation<string>(),

    // Memory from past posts and feedback
    memory: Annotation<string[]>(),

    // Context gathered by SearchAgent
    context: Annotation<string>(),

    // Raw content generated by CreatorAgent
    rawContent: Annotation<string>(),

    // Platform-tailored content (LinkedIn, IG, etc.)
    platformContent: Annotation<Record<string, {
        text: string;
        hashtags: string[];
        mediaRules: string;
    }>>(),

    // Safety and Compliance status
    safetyStatus: Annotation<{
        isSafe: boolean;
        flags: string[];
        reason?: string;
    }>(),

    // Performance analytics for current cycle
    analytics: Annotation<{
        engagementEstimate?: number;
        sentimentEstimate?: string;
    }>(),

    // Detailed feedback prompt for next iteration
    feedbackPrompt: Annotation<string>(),

    // Control flags
    nextAction: Annotation<"search" | "generate" | "orchestrate" | "verify" | "analyze" | "learn" | "end">()
});

export type AgentStateType = typeof AgentState.State;
