import { Annotation } from "@langchain/langgraph";

/**
 * Core state for the Socialyncara Intelligence Layer
 * Carries all user preferences so every agent can adapt its output.
 */
export const AgentState = Annotation.Root({
    // ─── Identity ────────────────────────────────────────────────────────────
    userId: Annotation<string>(),

    // ─── User preferences (read at intake, passed to every node) ─────────────
    postType: Annotation<
        "text_only" | "image_only" | "text_image" | "text_video" | "group"
    >(),
    preferredPlatforms: Annotation<string[]>(),
    platformPreferences: Annotation<Record<string, any>>(),  // per-platform settings
    useEmojis: Annotation<boolean>(),
    contentTone: Annotation<string>(),          // Formal | Casual | Friendly | Professional
    captionLength: Annotation<string>(),         // Short | Medium | Long
    hashtagIntensity: Annotation<string>(),      // Low | Medium | High
    automationLevel: Annotation<string>(),       // Manual | Semi-Auto | Full Auto

    // ─── Discovery phase ──────────────────────────────────────────────────────
    topic: Annotation<string>(),
    audience: Annotation<string>(),

    // ─── Memory from past posts and feedback ─────────────────────────────────
    memory: Annotation<string[]>(),

    // ─── Context gathered by ResearchAgent ───────────────────────────────────
    context: Annotation<string>(),

    // ─── Media acquired by MediaAgent ────────────────────────────────────────
    mediaUrls: Annotation<string[]>(),

    // ─── Raw content generated by CreatorAgent ───────────────────────────────
    rawContent: Annotation<string>(),

    // ─── Platform-tailored content from OrchestratorAgent ────────────────────
    platformContent: Annotation<Record<string, {
        text: string;
        hashtags: string[];
        mediaRules: string;
    }>>(),

    // ─── Safety and Compliance status ────────────────────────────────────────
    safetyStatus: Annotation<{
        isSafe: boolean;
        flags: string[];
        reason?: string;
    }>(),

    // ─── Performance analytics for current cycle ─────────────────────────────
    analytics: Annotation<{
        engagementEstimate?: number;
        sentimentEstimate?: string;
    }>(),

    // ─── Feedback prompt for next iteration ──────────────────────────────────
    feedbackPrompt: Annotation<string>(),

    // ─── Control flags ────────────────────────────────────────────────────────
    nextAction: Annotation<
        "search" | "generate" | "orchestrate" | "verify" | "analyze" | "learn" | "end"
    >(),
});

export type AgentStateType = typeof AgentState.State;
